name: CI/CD Pipeline

on: [push, pull_request]

permissions:
  contents: write

jobs: # the things being executed
  build:
    name: Generate Docs
    runs-on: windows-latest # which device on Github's server that you are running the Actions on
    steps:
    - uses: actions/checkout@master
      with:
        ref: ${{ github.ref }}
    - name: Run executable
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
        ./iceDocsGenerator.exe
    - name: Archive README.md
      uses: actions/upload-artifact@v2
      with:
        name: readme
        path: README.md