name: CI/CD Pipeline

on: [push, pull_request]
jobs: # the things being executed
  build:
    name: Generate Docs
    runs-on: windows-latest # which device on Github's server that you are running the Actions on
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run executable
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
        ./iceDocsGenerator.exe

  compile:
    name: Compile Code
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Run executable
      run: |
        Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force
        bash build.sh      