name: CI/CD Pipeline

on: [push, pull_request]
jobs: # the things being executed
  build:
    name: Generate Docs
    runs-on: windows-latest # which device on Github's server that you are running the Actions on
    steps:
    - name: "Run executable"
      run: iceDocsGenerator.exe