name: CI/CD Pipeline

on: [push, pull_request]
jobs: # the things being executed
  build:
    name: Generate Docs
    runs-on: ubuntu-latest # which device on Github's server that you are running the Actions on
    steps:
    - name: "Doxygen"
      run: |
        sudo apt-get install -y doxygen
        doxygen Doxyfile